import { randomUUID } from "node:crypto";
import { openRepositoryDb } from "../db/index.js";
import type { HistoricalAgentProvenance } from "../agents/provenance.js";
import type { AgentPromptPart } from "../agent/types.js";
import type { StructuredAcpError } from "./errors.js";

export type AcpSessionStatus = "starting" | "running" | "idle" | "cancelling" | "cancelled" | "failed" | "authentication_required" | "interrupted" | "recoverable" | "closed";
export type AcpPromptStatus = "running" | "completed" | "cancelled" | "failed" | "authentication_required" | "interrupted";
export interface AcpSessionRecord { id: string; repository_id: string; owner_type: string; owner_id: string; agent_id: string; agent_version: string; agent_provenance: HistoricalAgentProvenance; acp_session_id: string | null; capabilities: unknown; status: AcpSessionStatus; recovery_metadata: unknown; diagnostic: string | null; failure: StructuredAcpError | null; created_at: string; updated_at: string; started_at: string | null; ended_at: string | null }
export interface AcpPromptRecord { id: string; repository_id: string; session_id: string; prompt: string; content: string | AgentPromptPart[]; status: AcpPromptStatus; failure: StructuredAcpError | null; message_id: number | null; resubmission_of: string | null; cancellation_requested_at: string | null; diagnostic: string | null; started_at: string; ended_at: string | null }
export interface AcpEventRecord { id: number; repository_id: string; session_id: string; prompt_id: string | null; seq: number; type: string; normalized: unknown; raw_payload: unknown; created_at: string }

function json(value: unknown): string { return JSON.stringify(value ?? {}); }
function parse(value: unknown): unknown { try { return JSON.parse(String(value)); } catch { return value; } }
function session(row: Record<string, unknown>): AcpSessionRecord { return { ...(row as unknown as AcpSessionRecord), repository_id: String(row.repository_id), agent_provenance: parse(row.agent_provenance) as HistoricalAgentProvenance, capabilities: parse(row.capabilities), recovery_metadata: parse(row.recovery_metadata), failure: row.failure ? parse(row.failure) as StructuredAcpError : null }; }
function prompt(row: Record<string, unknown>): AcpPromptRecord { return { ...(row as unknown as AcpPromptRecord), repository_id: String(row.repository_id), content: parse(row.content) as string | AgentPromptPart[], failure: row.failure ? parse(row.failure) as StructuredAcpError : null }; }
function event(row: Record<string, unknown>): AcpEventRecord { return { ...(row as unknown as AcpEventRecord), repository_id: String(row.repository_id), normalized: parse(row.normalized), raw_payload: parse(row.raw_payload) }; }

export function createSession(repositoryId: string, input: { ownerType: string; ownerId: string; agentId: string; agentVersion: string; agentProvenance?: HistoricalAgentProvenance; capabilities?: unknown; recoveryMetadata?: unknown }, machineDir?: string): AcpSessionRecord {
  const db = openRepositoryDb(repositoryId, machineDir); const id = randomUUID();
  db.prepare("INSERT INTO acp_sessions (id, repository_id, owner_type, owner_id, agent_id, agent_version, agent_provenance, capabilities, recovery_metadata) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").run(id, repositoryId, input.ownerType, input.ownerId, input.agentId, input.agentVersion, json(input.agentProvenance), json(input.capabilities), json(input.recoveryMetadata));
  return getSession(repositoryId, id, machineDir)!;
}
export function getSession(repositoryId: string, id: string, machineDir?: string): AcpSessionRecord | undefined { const row = openRepositoryDb(repositoryId, machineDir).prepare("SELECT * FROM acp_sessions WHERE id = ? AND repository_id = ?").get(id, repositoryId) as Record<string, unknown> | undefined; return row ? session(row) : undefined; }
export function listSessions(repositoryId: string, machineDir?: string): AcpSessionRecord[] { return (openRepositoryDb(repositoryId, machineDir).prepare("SELECT * FROM acp_sessions WHERE repository_id = ? ORDER BY created_at DESC").all(repositoryId) as Record<string, unknown>[]).map(session); }
export function listSessionsForOwner(repositoryId: string, ownerType: string, ownerId: string, machineDir?: string): AcpSessionRecord[] { return (openRepositoryDb(repositoryId, machineDir).prepare("SELECT * FROM acp_sessions WHERE repository_id = ? AND owner_type = ? AND owner_id = ? ORDER BY created_at").all(repositoryId, ownerType, ownerId) as Record<string, unknown>[]).map(session); }
export function updateSession(repositoryId: string, id: string, input: Partial<Pick<AcpSessionRecord, "acp_session_id" | "status" | "diagnostic" | "failure" | "started_at" | "ended_at">> & { capabilities?: unknown; recovery_metadata?: unknown }, machineDir?: string): AcpSessionRecord {
  const current = getSession(repositoryId, id, machineDir); if (!current) throw new Error(`ACP session not found: ${id}`);
  openRepositoryDb(repositoryId, machineDir).prepare("UPDATE acp_sessions SET acp_session_id = ?, status = ?, diagnostic = ?, failure = ?, capabilities = ?, recovery_metadata = ?, started_at = ?, ended_at = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND repository_id = ?").run(input.acp_session_id ?? current.acp_session_id, input.status ?? current.status, input.diagnostic === undefined ? current.diagnostic : input.diagnostic, input.failure === undefined ? (current.failure ? json(current.failure) : null) : input.failure ? json(input.failure) : null, json(input.capabilities ?? current.capabilities), json(input.recovery_metadata ?? current.recovery_metadata), input.started_at ?? current.started_at, input.ended_at ?? current.ended_at, id, repositoryId);
  return getSession(repositoryId, id, machineDir)!;
}
export function createPrompt(repositoryId: string, sessionId: string, content: string | AgentPromptPart[], machineDir?: string, input: { messageId?: number; resubmissionOf?: string } = {}): AcpPromptRecord { if (!getSession(repositoryId, sessionId, machineDir)) throw new Error(`ACP session not found: ${sessionId}`); const id = randomUUID(); const text = typeof content === "string" ? content : content.map((part) => part.type === "text" ? part.text : "[image]").join(""); openRepositoryDb(repositoryId, machineDir).prepare("INSERT INTO acp_prompts (id, repository_id, session_id, prompt, content, message_id, resubmission_of) VALUES (?, ?, ?, ?, ?, ?, ?)").run(id, repositoryId, sessionId, text, json(content), input.messageId ?? null, input.resubmissionOf ?? null); return getPrompt(repositoryId, id, machineDir)!; }
export function getPrompt(repositoryId: string, id: string, machineDir?: string): AcpPromptRecord | undefined { const row = openRepositoryDb(repositoryId, machineDir).prepare("SELECT * FROM acp_prompts WHERE id = ? AND repository_id = ?").get(id, repositoryId) as Record<string, unknown> | undefined; return row ? prompt(row) : undefined; }
export function updatePrompt(repositoryId: string, id: string, input: Partial<Pick<AcpPromptRecord, "status" | "diagnostic" | "failure" | "ended_at" | "cancellation_requested_at">>, machineDir?: string): AcpPromptRecord { const current = getPrompt(repositoryId, id, machineDir); if (!current) throw new Error(`ACP prompt not found: ${id}`); openRepositoryDb(repositoryId, machineDir).prepare("UPDATE acp_prompts SET status = ?, diagnostic = ?, failure = ?, ended_at = ?, cancellation_requested_at = ? WHERE id = ? AND repository_id = ?").run(input.status ?? current.status, input.diagnostic === undefined ? current.diagnostic : input.diagnostic, input.failure === undefined ? (current.failure ? json(current.failure) : null) : input.failure ? json(input.failure) : null, input.ended_at ?? current.ended_at, input.cancellation_requested_at ?? current.cancellation_requested_at, id, repositoryId); return getPrompt(repositoryId, id, machineDir)!; }
export function listSessionPrompts(repositoryId: string, sessionId: string, machineDir?: string): AcpPromptRecord[] { if (!getSession(repositoryId, sessionId, machineDir)) return []; return (openRepositoryDb(repositoryId, machineDir).prepare("SELECT * FROM acp_prompts WHERE repository_id = ? AND session_id = ? ORDER BY started_at").all(repositoryId, sessionId) as Record<string, unknown>[]).map(prompt); }
export function appendEvent(repositoryId: string, sessionId: string, promptId: string | null, type: string, normalized: unknown, rawPayload: unknown, machineDir?: string): AcpEventRecord { const db = openRepositoryDb(repositoryId, machineDir); if (!getSession(repositoryId, sessionId, machineDir)) throw new Error(`ACP session not found: ${sessionId}`); if (promptId && !getPrompt(repositoryId, promptId, machineDir)) throw new Error(`ACP prompt not found: ${promptId}`); const seq = (db.prepare("SELECT COALESCE(MAX(seq), 0) + 1 AS next FROM acp_events WHERE repository_id = ? AND session_id = ?").get(repositoryId, sessionId) as { next: number }).next; const info = db.prepare("INSERT INTO acp_events (repository_id, session_id, prompt_id, seq, type, normalized, raw_payload) VALUES (?, ?, ?, ?, ?, ?, ?)").run(repositoryId, sessionId, promptId, seq, type, json(normalized), json(rawPayload)); return getEvent(repositoryId, Number(info.lastInsertRowid), machineDir)!; }
export function getEvent(repositoryId: string, id: number, machineDir?: string): AcpEventRecord | undefined { const row = openRepositoryDb(repositoryId, machineDir).prepare("SELECT * FROM acp_events WHERE id = ? AND repository_id = ?").get(id, repositoryId) as Record<string, unknown> | undefined; return row ? event(row) : undefined; }
export function listSessionEvents(repositoryId: string, sessionId: string, machineDir?: string): AcpEventRecord[] { return (openRepositoryDb(repositoryId, machineDir).prepare("SELECT * FROM acp_events WHERE repository_id = ? AND session_id = ? ORDER BY seq").all(repositoryId, sessionId) as Record<string, unknown>[]).map(event); }
export function interruptActiveSessions(repositoryId: string, machineDir?: string): void { const db = openRepositoryDb(repositoryId, machineDir); db.prepare("UPDATE acp_sessions SET status = 'interrupted', diagnostic = 'Daemon stopped before the ACP session completed', ended_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE repository_id = ? AND status IN ('starting', 'running', 'cancelling')").run(repositoryId); db.prepare("UPDATE acp_prompts SET status = 'interrupted', diagnostic = 'Daemon stopped before the ACP prompt completed', ended_at = CURRENT_TIMESTAMP WHERE repository_id = ? AND status = 'running'").run(repositoryId); db.prepare("UPDATE permission_requests SET status = 'interrupted', diagnostic = 'Daemon stopped before the ACP request completed', resolved_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP WHERE repository_id = ? AND status = 'pending'").run(repositoryId); }
