export const queryKeys = {
  diagnostics: ["diagnostics"] as const,
  repositories: ["repositories"] as const,
  registry: ["registry"] as const,
  installedAgents: ["installed-agents"] as const,
  installation: (id: string) => ["installation", id] as const,
  agentAuthentication: (id: string, version: string, installationId = "") => ["agent-authentication", id, version, installationId] as const,
  tasks: (repositoryId: string | null = null) => ["tasks", repositoryId] as const,
  task: (slug: string, repositoryId: string | null = null) => ["task", repositoryId, slug] as const,
  taskDiff: (slug: string, repositoryId: string | null = null) => ["task", repositoryId, slug, "diff"] as const,
  taskRuns: (slug: string, repositoryId: string | null = null) => ["task", repositoryId, slug, "runs"] as const,
  specMessages: (slug: string, repositoryId: string | null = null) => ["task", repositoryId, slug, "spec-messages"] as const,
  threads: (archived: boolean, repositoryId: string | null = null) => ["threads", repositoryId, { archived }] as const,
  thread: (id: string, repositoryId: string | null = null) => ["thread", repositoryId, id] as const,
  files: (id: string, repositoryId: string | null = null) => ["thread", repositoryId, id, "files"] as const,
  file: (id: string, path: string, repositoryId: string | null = null) => ["thread", repositoryId, id, "file", path] as const,
  permissions: (id: string, repositoryId: string | null = null) => ["thread", repositoryId, id, "permissions"] as const,
  attachments: (id: string, repositoryId: string | null = null) => ["thread", repositoryId, id, "attachments"] as const,
  chatAgents: ["chat-agents"] as const,
  workflowProfiles: (repositoryId: string) => ["workflow-profiles", repositoryId] as const,
};
