export const queryKeys = {
  repositories: ["repositories"] as const,
  registry: ["registry"] as const,
  installedAgents: ["installed-agents"] as const,
  installation: (id: string) => ["installation", id] as const,
  tasks: (repositoryId: string | null = null) => ["tasks", repositoryId] as const,
  task: (slug: string, repositoryId: string | null = null) => repositoryId ? ["task", repositoryId, slug] as const : ["task", slug] as const,
  taskDiff: (slug: string) => ["task", slug, "diff"] as const,
  specMessages: (slug: string) => ["task", slug, "spec-messages"] as const,
  threads: (archived: boolean, repositoryId: string | null = null) => repositoryId ? ["threads", repositoryId, { archived }] as const : ["threads", { archived }] as const,
  thread: (id: string, repositoryId: string | null = null) => repositoryId ? ["thread", repositoryId, id] as const : ["thread", id] as const,
  files: (id: string) => ["thread", id, "files"] as const,
  file: (id: string, path: string) => ["thread", id, "file", path] as const,
  permissions: (id: string) => ["thread", id, "permissions"] as const,
  attachments: (id: string) => ["thread", id, "attachments"] as const,
  chatAgents: ["chat-agents"] as const,
};
