ALTER TABLE chat_messages ADD COLUMN repository_id TEXT;
ALTER TABLE chat_attachments ADD COLUMN repository_id TEXT;
ALTER TABLE acp_sessions ADD COLUMN repository_id TEXT;
ALTER TABLE acp_prompts ADD COLUMN repository_id TEXT;
ALTER TABLE acp_events ADD COLUMN repository_id TEXT;
ALTER TABLE permission_requests ADD COLUMN repository_id TEXT;
CREATE INDEX idx_chat_threads_repository ON chat_threads(repository_id);
CREATE INDEX idx_chat_messages_repository_thread ON chat_messages(repository_id, thread_id);
CREATE INDEX idx_chat_attachments_repository_thread ON chat_attachments(repository_id, thread_id);
CREATE INDEX idx_acp_sessions_repository ON acp_sessions(repository_id);
CREATE INDEX idx_acp_prompts_repository_session ON acp_prompts(repository_id, session_id);
CREATE INDEX idx_acp_events_repository_session ON acp_events(repository_id, session_id);
CREATE INDEX idx_permission_requests_repository_thread ON permission_requests(repository_id, thread_id);
