ALTER TABLE tasks ADD COLUMN repository_id_v2 TEXT;
ALTER TABLE runs ADD COLUMN repository_id TEXT;
ALTER TABLE run_operations ADD COLUMN repository_id TEXT;
ALTER TABLE run_events ADD COLUMN repository_id TEXT;
ALTER TABLE spec_messages ADD COLUMN repository_id TEXT;
ALTER TABLE spec_author_sessions ADD COLUMN repository_id_v2 TEXT;
ALTER TABLE spec_author_operations ADD COLUMN repository_id TEXT;
CREATE INDEX idx_tasks_repository_slug ON tasks(repository_id_v2, slug);
CREATE UNIQUE INDEX idx_tasks_repository_slug_unique ON tasks(repository_id_v2, slug);
CREATE INDEX idx_runs_repository_task ON runs(repository_id, task_id);
CREATE INDEX idx_run_operations_repository_run ON run_operations(repository_id, run_id);
CREATE INDEX idx_run_events_repository_run ON run_events(repository_id, run_id);
CREATE INDEX idx_spec_messages_repository_task ON spec_messages(repository_id, task_id);
CREATE INDEX idx_spec_author_sessions_repository_task ON spec_author_sessions(repository_id_v2, task_id);
CREATE INDEX idx_spec_author_operations_repository_session ON spec_author_operations(repository_id, author_session_id);
