import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const tasks = sqliteTable("tasks", {
  id: integer().primaryKey({ autoIncrement: true }),
  slug: text().notNull(),
  title: text().notNull(),
  status: text().notNull(),
  specMarkdown: text("spec_markdown").notNull(),
  retryCount: integer("retry_count").notNull(),
  lastFailure: text("last_failure"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});
export const chatThreads = sqliteTable("chat_threads", {
  id: text().primaryKey(),
  repositoryId: text("repository_id"),
  repoRoot: text("repo_root").notNull(),
  cwd: text().notNull(),
  agentId: text("agent_id").notNull(),
  agentVersion: text("agent_version").notNull(),
  title: text().notNull(),
  status: text().notNull(),
  archived: integer().notNull(),
  pinned: integer().notNull(),
  taskSlug: text("task_slug"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  lastMessageAt: text("last_message_at"),
  scratchMarkdown: text("scratch_markdown").notNull(),
  agentProvenance: text("agent_provenance").notNull(),
  sessionConfigOptions: text("session_config_options").notNull(),
  sessionModes: text("session_modes"),
  sessionInitialized: integer("session_initialized").notNull(),
  failure: text(),
});
export const chatMessages = sqliteTable("chat_messages", {
  id: integer().primaryKey({ autoIncrement: true }),
  threadId: text("thread_id").notNull(),
  role: text().notNull(),
  content: text().notNull(),
  attachmentIds: text("attachment_ids").notNull(),
  promptStatus: text("prompt_status"),
  failure: text(),
  createdAt: text("created_at").notNull(),
});
export const acpSessions = sqliteTable("acp_sessions", {
  id: text().primaryKey(),
  ownerType: text("owner_type").notNull(),
  ownerId: text("owner_id").notNull(),
  agentId: text("agent_id").notNull(),
  agentVersion: text("agent_version").notNull(),
  acpSessionId: text("acp_session_id"),
  capabilities: text().notNull(),
  status: text().notNull(),
  recoveryMetadata: text("recovery_metadata").notNull(),
  diagnostic: text(),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
  startedAt: text("started_at"),
  endedAt: text("ended_at"),
  agentProvenance: text("agent_provenance").notNull(),
  failure: text(),
});
